# Generated by Django 5.2.10 on 2026-02-03 13:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SQLTrainingExample",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("question", models.TextField()),
                ("sql_query", models.TextField()),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "sql_training_examples",
            },
        ),
        migrations.CreateModel(
            name="Conversation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("state", models.JSONField(blank=True, default=dict)),
                ("last_activity", models.DateTimeField(auto_now=True, db_index=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "conversations",
                "indexes": [
                    models.Index(
                        fields=["last_activity"], name="conversatio_last_ac_f87419_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="conversatio_created_694913_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Lead",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("conversation_id", models.UUIDField(db_index=True)),
                ("first_name", models.CharField(blank=True, max_length=100, null=True)),
                ("last_name", models.CharField(blank=True, max_length=100, null=True)),
                ("email", models.EmailField(blank=True, max_length=255, null=True)),
                ("phone", models.CharField(blank=True, max_length=50, null=True)),
                ("preferences", models.JSONField(blank=True, default=dict)),
                (
                    "lead_source",
                    models.CharField(
                        choices=[
                            ("website_chat", "Website Chat"),
                            ("referral", "Referral"),
                            ("direct", "Direct"),
                        ],
                        default="website_chat",
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "leads",
                "indexes": [
                    models.Index(fields=["email"], name="leads_email_554d9f_idx"),
                    models.Index(
                        fields=["conversation_id"], name="leads_convers_f7baf5_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("project_name", models.CharField(db_index=True, max_length=255)),
                (
                    "developer_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("city", models.CharField(db_index=True, max_length=100)),
                ("country", models.CharField(max_length=2)),
                (
                    "property_type",
                    models.CharField(
                        blank=True,
                        choices=[("apartment", "Apartment"), ("villa", "Villa")],
                        max_length=50,
                        null=True,
                    ),
                ),
                ("bedrooms", models.IntegerField(blank=True, db_index=True, null=True)),
                ("bathrooms", models.IntegerField(blank=True, null=True)),
                (
                    "price_usd",
                    models.DecimalField(
                        blank=True,
                        db_index=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "area_sqm",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("unit_type", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "completion_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("available", "Available"),
                            ("off_plan", "Off Plan"),
                            ("under_construction", "Under Construction"),
                            ("completed", "Completed"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                ("completion_date", models.DateField(blank=True, null=True)),
                ("features", models.JSONField(blank=True, default=list)),
                ("facilities", models.JSONField(blank=True, default=list)),
                ("description", models.TextField(blank=True, null=True)),
                ("data_source", models.CharField(default="csv_import", max_length=50)),
                (
                    "import_batch_id",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("data_quality_score", models.FloatField(default=1.0)),
                ("is_valid", models.BooleanField(default=True)),
                ("validation_errors", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "projects",
                "indexes": [
                    models.Index(
                        fields=["city", "bedrooms", "price_usd"],
                        name="projects_city_bc4868_idx",
                    ),
                    models.Index(
                        fields=["is_valid"], name="projects_is_vali_fb11a1_idx"
                    ),
                    models.Index(
                        fields=["property_type"], name="projects_propert_9823f4_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Booking",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("conversation_id", models.UUIDField(db_index=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("confirmed", "Confirmed"),
                            ("cancelled", "Cancelled"),
                            ("completed", "Completed"),
                        ],
                        default="pending",
                        max_length=50,
                    ),
                ),
                ("booking_date", models.DateTimeField(auto_now_add=True)),
                ("visit_date", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "lead",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookings",
                        to="domain.lead",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookings",
                        to="domain.project",
                    ),
                ),
            ],
            options={
                "db_table": "visit_bookings",
                "indexes": [
                    models.Index(
                        fields=["status"], name="visit_booki_status_4c95ba_idx"
                    ),
                    models.Index(
                        fields=["conversation_id"],
                        name="visit_booki_convers_157548_idx",
                    ),
                ],
            },
        ),
    ]
