# Generated by Django 5.2.11 on 2026-02-04 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("domain", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="image_url",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
