web: cd src && gunicorn config.wsgi:application --bind 0.0.0.0:$PORT
release: cd src && python manage.py migrate && python manage.py import_properties ../data/Property_sales_agent_-_Challenge.csv --batch-size 500
